name: "Example unfork forked action"
on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    env:
      SHA: $(echo ${GITHUB_SHA} | cut -c1-7)

    steps:
    - uses: actions/checkout@v1

    - name: "kustomize build migrations"
      uses: marccampbell/kustomize-github-action@set-image
      with:
        kustomize_version: "2.0.3"
        kustomize_build_dir: "migrations/kustomize/overlays/staging"
        kustomize_output_file: "gitops-deploy/staging/schema.yaml"