name: "Proaction"
description: "Create more reliable, maintainable, and secure GitHub Actions"
inputs:
  workflow-files:
    description: "Workflow Files"
    required: false
    default: ".github/workflows/**"
  github-token:
    description: "GitHub API Token"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
  args:
    - "/proaction scan ${{ inputs.workflow-files }}"
