name: "Proaction"
description: "Create more reliable, maintainable, and secure GitHub Actions"
inputs:
  workflow-files:
    description: "Workflow Files"
    required: false
    default: ".github/workflows/**"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "/proaction scan ${{inputs.workflow-files}}"
