on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-proaction:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13.8"

      - name: setup env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash

      - uses: actions/checkout@master

      - run: make test proaction

      - uses: actions/upload-artifact@v1
        with:
          name: proaction
          path: bin/proaction

  validate:
    runs-on: ubuntu-18.04
    needs: build-proaction
    steps:
      - name: download proadtion binary
        uses: actions/download-artifact@v1
        with:
          name: proaction
          path: bin/

      - run: chmod +x bin/proaction

