on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - releases/**-alpha

jobs:
  build-proaction:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13.8"

      - name: setup env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash

      - uses: actions/checkout@master

      - run: make test proaction

      - uses: actions/upload-artifact@v1
        with:
          name: proaction
          path: bin/proaction

  validate:
    runs-on: ubuntu-18.04
    needs: build-proaction
    steps:
      - name: download proaction binary
        uses: actions/download-artifact@v1
        with:
          name: proaction
          path: bin/

      - run: chmod +x bin/proaction

  goreleaser:
    runs-on: ubuntu-latest
    needs:
      - validate
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-go@v1
        with:
          go-version: "1.13.8"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        if: contains(github.ref, "release")
        with:
          version: latest
          args: release --rm-dist --snapshot --config deploy/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}