on:
  push:
    branches:
      - issue/30

jobs:
  run-proaction:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: proactionhq/proaction/action@issue/30
        with:
          workflow-files: ".github/workflows/build-test-deploy.yaml"
      - uses: peter-evans/create-pull-request@v2
        with:
          commit-message: "[proaction] updating workflow"
          title: Updating workflow from Proaction
